---
app: pubsub
version: 1.0
topicDir: /Users/sahanakuchur/Desktop/Final/EventBasedPubSub/TopicsRootFolder
nodes:
  - ip: 192.168.1.114
    port: 6000
  - ip: 192.168.1.114
    port: 6005
  - ip: 192.168.1.114
    port: 6010
