---
app: pubsub
version: 1.0
topicDir: /Users/sahanakuchur/Desktop/Final/EventBasedPubSub/TopicsRootFolder
nodes:
  - ip: 172.17.0.2
    port: 6000
  - ip: 172.17.0.3
    port: 6000
  - ip: 172.17.0.4
    port: 6000
